### ISSUE TITLE
How to provider the delay in hour and minute ?

### ISSUE THREAD

**Issue by ua4ever** [brunocalou/Timer#1]
I don't understand how to write the code to delay in hour or minute :(

**Comment by brunocalou** [comment]
Hello

The methods expect a time in milliseconds, so you should pass the time you want in milliseconds. 

Example: 1 minute has 60 seconds. 1 second has 1000ms. So 1 minute is 1 * 60 * 1000 milliseconds.
Example: 15 minutes has 15 * 60 seconds. 1 second has 1000ms. So 15 minutes is 15 * 60 * 1000 milliseconds.

The same for hours
Example: 1 hour has 60 minutes. 1 minute has 60 seconds. 1 second has 1000ms. So, 1 hour is 1 * 60 * 60 * 1000
Example: 3 hours has 3 * 60 minutes. 1 minute has 60 seconds. 1 second has 1000ms. So, 3 hours is 3 * 60 * 60 * 1000

To make it easier, drop this function on your code and use it as you wish:
```c++
/**
 * Convert hours, minutes, and seconds to milliseconds
 */
unsigned long toMs(unsigned int hours=0, unsigned int minutes=0, unsigned int seconds=0) {
    return (((hours * 60 + minutes) * 60) + seconds) * 1000;
}
```

## Usage
```c++
...
  // The timer will repeat every 3 hours
  timer.setInterval(toMs(3)); 
...
  // The timer will repeat every 1h 15m
  timer.setInterval(toMs(1, 15)); 
...
  // The timer will repeat every 30 minutes
  timer.setInterval(toMs(0, 30)); 
...
  // The timer will repeat every 4h 15m 30s
  timer.setInterval(toMs(4, 15, 30)); 
```
