### ISSUE TITLE
Timers only run 65536 times

### ISSUE THREAD

**Issue by JMedow** [brunocalou/Timer#11]
in Timer::update repeat_count decrements from -1 until it overflows and hits zero, stopping the counter.  The fix would be to add `if(repeat_count > 0)
  repeat_count -= 1`

**Comment by brunocalou** [comment]
True, can you open a PR fixing it, please?

**Comment by JMedow** [comment]
I've opened the PR.

**Comment by brunocalou** [comment]
Thank you!
