### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by phi1knight** [brunocalou/Timer#14]
Hi Bruno,
I'm having an issue where the error is "Including this file is deprecated. Please #include <arduino-timer.h> instead." Does this mean there is no longer support for this timer? I've written my code to suit using your library as it worked perfectly with my code before but now sadly its not. I'm using the same code where it worked previously but now on an ESP32 is that the issue.
Many thanks for your time.

**Comment by brunocalou** [comment]
Hello,
Could you please post a sample of the code you're trying to compile? This `arduino-timer.h` file is from [another library](https://github.com/contrem/arduino-timer)

**Comment by phi1knight** [comment]
Below is the error report generated by the IDE, I'll attach some of the code in another post.
timerManager IS installed in the libraries folder in the same way as others so I can't understand why it says its not found. I'm trying to compile for an ESP32 just in case that should cause an issue.

In file included from C:\Users\phil.knight\Downloads\TankLevelsBetaV6_1_2_ESP32\TankLevelsBetaV6_1_2_ESP32.ino:25:
c:\Arduino\libraries\arduino-timer\src/timer.h:1:2: error: #error "Including this file is deprecated. Please #include <arduino-timer.h> instead."
 #error "Including this file is deprecated. Please #include <arduino-timer.h> instead."
  ^~~~~
C:\Users\phil.knight\Downloads\TankLevelsBetaV6_1_2_ESP32\TankLevelsBetaV6_1_2_ESP32.ino:26:10: fatal error: timerManager.h: No such file or directory
 #include <timerManager.h>
                 ^~~~~~~~~~~~~~~~
compilation terminated.

**Comment by phi1knight** [comment]
below is the (what I deem relevant to the problem but if you need more let me know) sections of code for the inclusion of header files etc. I have been using this code as it is for a while with no problem but on a MacBook. However, its an old machine and now wont support the USB drivers required for the ESP32 or the IDE has updated and not supported by the OS anymore. The machine I am using now is a windows machine and this is the first attempt at using it to compile this code. The relevant libraries have been installed (although I have noted that your library isn't listed in the library manager??)


#include <Arduino.h>
#define BLYNK_SSL_USE_LETSENCRYPT
#include <BlynkSimpleEsp32.h>
#include <Wire.h>
#include <arduino-timer.h>
#include <timer.h>
#include <timerManager.h>
#include <Adafruit_ADS1X15.h>
//#include <ArduinoOTA.h>                                         //added for OTA

//* DS18B20 Temperature Sensor 
#include <OneWire.h>
#include <DallasTemperature.h> 
#define  ONE_WIRE_BUS 14                                      // DS18B20 ESP8266 GPIO2 D4
OneWire  oneWire(ONE_WIRE_BUS);
DallasTemperature DS18B20(&oneWire);
Adafruit_ADS1115 ads;

//#define LED_BUILTIN 13
#define DEBUG 1
    


    //** Blynk server and Wifi connection properties
    // Set password to "" for open networks.
    char ssid[] = "";		                                //local wifi network SSID
    char pass[] = "";			                          //local network password
   // ipad  char auth[] = "";     //You should get Authority Token in your email.  
   char auth[] = "";              // iphone local server
   BlynkTimer timer;                                               //config timer
   Timer OverRunTimer;
   Timer UVRunTimer;

**Comment by brunocalou** [comment]
There is a `timer.h` file on the `arduino-timer` library, and when you try to include it, it will show you this exact same error. [See the original file here](https://github.com/contrem/arduino-timer/blob/master/src/timer.h).

Are you using this `arduino-timer` library? If not, can you uninstall it and remove the `#include <arduino-timer.h>` line?

If you cannot uninstall it, try using the full path of the `timer.h` file. Something like that
```cpp
#include "C:\Arduino\libraries\Timer\timer.h"
```

**Comment by phi1knight** [comment]
Uninstalling Arduino-Timer has sorted that issue and putting the file path in the #include statement has sorted the rest. I also discovered i have two library folders, one on the main C drive and one as a user on the C drive. Consolidating those folders into one has improved things as well. Many thanks.
