### ISSUE TITLE
Incorrect documentation - stopped vs. paused

### ISSUE THREAD

**Issue by nullpainter** [brunocalou/Timer#2]
In the documentation for the `Timer` class, you note that `void stop()` pauses the timer, whereas `void pause()` resets the timer.

Are these function descriptions the wrong way around? Although, documentation for a function called `stop` which says "the timer will not stop" is also confusing. 

Is a call to `stop()` then `start()` effective as a reset?

**Comment by nullpainter** [comment]
Ah, you actually have a `reset()` function on the `Timer` class!

**Comment by brunocalou** [comment]
My bad, I wrote it a long time ago.
I'll update the docs when I have some spare time.

Thank you!

**Comment by brunocalou** [comment]
Done! Hope it's more clear now
