### ISSUE TITLE
Callback function doesn't allow parameters

### ISSUE THREAD

**Issue by RalphBacon** [brunocalou/Timer#3]
Hi Bruno
I really like this library of yours and will be using it as part of my Universal Timer project very shortly. I did notice (but am not surprised) that the callback function does not allow parameters to be supplied to the callback function - I have to write a wrapper that then supplies the parameters.

Is there any way that you could allow a construct such as:
timer.setCallback(1000, myFunctionHere(24, 85.1, "GO", true);

Or is this more a restriction of C++. I have to admit I have not inspected your code as I'm tied up creating the YouTube video for the Universal Timer project right now! Very lazy of me, I know.

Anyway, if there is a way of doing the above do let me know (I don't mind forking the code) and thanks again for a great library. Tudo bem!

Ralph Bacon
www.youtube.com/ralphbacon

**Comment by brunocalou** [comment]
Hi Ralph,

Thank you for using my library 😄 

There is a way using C++11 and it requires no change to the source code.
You could wrap your callback using a lambda function. It is pretty much the same process you are already doing, but less verbose. I have quickly tested it using an online compiler and it worked as expected, so if your arduino environment is using C++11, it should work too.

```C++
#include <iostream>
// The function that calls the callback. It is pretty much the same
// concept used internally in the library
void callFunction(void (*function)(void)) {
  function();
}

// Your callback function with parameters
void theFunction(int a) {
  std::cout << "a = " << a << std::endl;
}

int main() {
  // Call the callback function. Note that the lambda function just
  // calls our callback function with arguments
  callFunction([]() { theFunction(1); });
}
```

So using the library, it should be used like that

```C++
timer.setCallback(1000, []() { myFunctionHere(24, 85.1, "GO", true); });
```

**Comment by RalphBacon** [comment]
Hi Bruno

 

Thanks so much for such a quick reply. Muito obriagdo.

 

I have tried out your suggestion of using lambdas and it works just as you say. In fact, I can put any code in the callback we want (eg multiple lines of code) and it all works fine. 

 

For a trivial example, I can now write:

 

timer.setCallback([]() {

                beep(NOTE_C7, 50);

                delay(65);

                beep(NOTE_B6, 50);

           });

 

Thank you again, and I hope my viewers will download you library and experiment with it.

 

Best Regards

Ralph S Bacon

https://www.youtube.com/ralphbacon

**Comment by brunocalou** [comment]
Hi Ralph!

I'm happy it worked seamlessly 😄 

Best of luck on your channel!
