### ISSUE TITLE
repeat forever does not work with the current Arduino compiler

### ISSUE THREAD

**Issue by jum** [brunocalou/Timer#5]
The repeat_count and total_repeat_count members are supposed to be able to hold the value "-1" to denote repeating forever. But unfortunately these members (and the final arg of setInterval) are declared unsigned, which does not work with current compilers (tested on a Mega board). Changing these to plain int makes it work.

**Comment by Szelwin** [comment]
Does it mean that when you don't change repeat_count or total_repeat_count and you just set the Timer interval and callback, then update it in void loop() it will not run forever?

**Comment by jum** [comment]
I did not set repeat_cound nor total_repeat_count, just using the default argument of setInterval to get an infinite repeat count. In my case it stops after about 64K intervals.

**Comment by Szelwin** [comment]
Thank you for this information, now I know what's been messing my project.

**Comment by brunocalou** [comment]
Thanks, @jum, you're absolutely right. I'll release a new version fixing this issue
