### ISSUE TITLE
Will this library work with Arduino when configured and used with ESP32?

### ISSUE THREAD

**Issue by rowifi** [brunocalou/Timer#7]
I'd like to use this but see no mention of ESP32. From what I've seen it uses the generic millis so hopefully..
I added it to the libraries as instructed - but don't see it appearing in the list when using library manager .

**Comment by brunocalou** [comment]
Hello,

Have you closed and reopened the Arduino IDE?

If I recall properly, the IDE reads the libraries just on startup

**Comment by rowifi** [comment]
It seems to work fine. ESP 32 Thanks
