### ISSUE TITLE
cant setInterval(time) morethan 65000ms

### ISSUE THREAD

**Issue by comfortplusplus** [brunocalou/Timer#9]
warning: overflow in implicit constant conversion [-Woverflow]

**Comment by comfortplusplus** [comment]
also timer stops working if value is set above 32000
might this be the problem:?
https://forum.arduino.cc/t/having-trouble-warning-overflow-in-implicit-constant-conversion-woverflow/538875
cause i have an atmega based board.

**Comment by brunocalou** [comment]
That's weird...

The lib uses `unsigned long` to store the time. In your code, were you using another type, like `int`?

```cpp
int interval = 123;

timer.setInterval(interval); 
```

Maybe this would trigger this warning and prevent it from working with large numbers.

Can you provide a code snippet reproducing this error?

**Comment by comfortplusplus** [comment]
yes i was using int, but i just tried setting it with unsigned long and the timer still malfunctions, but i didnt get the woverflow error.

heres the reproduction
run the code with time2 set to 32000 and then 33000, then compare the results.


#include <timer.h>
#include <timerManager.h>

Timer timer1;
Timer timer2;

unsigned long time1 = 10000;
unsigned long time2 = 32000;

void setup() {
  Serial.begin(9600);

  timer1.setInterval(time1);
  timer1.setCallback(timer1off);
  timer2.setInterval(time2);
  timer2.setCallback(timer2off);

  timer1.start();
}

void loop() {
delay(1000);

timer1.update();
timer2.update();

Serial.println("");
Serial.println("Timer 1");
Serial.println(timer1.getElapsedTime()/1000);
Serial.println("Timer 2");
Serial.println(timer2.getElapsedTime()/1000);
Serial.println("");
}

void timer1off(){
  timer1.pause();
  timer1.reset();
  timer2.start();  
  }
void timer2off(){
  timer2.pause();
  timer2.reset();
  timer1.start();
  }

**Comment by brunocalou** [comment]
What exactly is wrong? What is the expected output and what is the real one?

There are a few issues with this code... `setInterval` will call the callback every time, since you want to call just once and then start the other timer, you could use `setTimeout`.

Also, the delay is not needed.

I changed the code and ran it on an online simulator. It worked like a charm, could you test it on your board?

```cpp
#include <timer.h>
#include <timerManager.h>

Timer timer1;
Timer timer2;
Timer printOftenTimer;

unsigned long time1 = 10000;
unsigned long time2 = 33000;

void setup() {
  Serial.begin(9600);

  timer1.setTimeout(time1);
  timer1.setCallback(timer1off);

  timer2.setTimeout(time2);
  timer2.setCallback(timer2off);

  printOftenTimer.setInterval(500);
  printOftenTimer.setCallback([] {
    Serial.println("");
    Serial.println("Timer 1");
    Serial.println(timer1.getElapsedTime()/1000);
    Serial.println("Timer 2");
    Serial.println(timer2.getElapsedTime()/1000);
    Serial.println("");
  });

  printOftenTimer.start();

  timer1.start();
}

void loop() {
  //Update all the timers at once
  TimerManager::instance().update();
}

void timer1off(){
  Serial.println("finishing timer 1");
  Serial.println("starting timer 2");
  timer2.start();
}
void timer2off(){
  Serial.println("finishing timer 2");
  Serial.println("starting timer 1");
  timer1.start();
}
```

**Comment by comfortplusplus** [comment]
ok heres how it went are you ready?
1. timer 1 starts
2. timer 1 stops
3. timer 2 starts and it never stops

**Comment by comfortplusplus** [comment]
i have two boards and i tried it on both

**Comment by comfortplusplus** [comment]
oh yes sorry your code is working i wasnt paying attention
my code wasnt working for some reason dunno why
and thanks for the fast responce you didnt had to

**Comment by comfortplusplus** [comment]
ok im trying to make the arduino do:

turn on the relay 
wait 10 seconds
turn off the relay 
wait 33 seconds or more
repeat


i dont think the code you provided can do this


i did achieve to do this with my code i cant go above 32 seconds, if i did go above 32 this would happen:

turns on the relay 
waits 10 seconds
turns off the relay forever


my code behaviur at 32s or lower:

turn on the relay 
wait 10 seconds
turn off the relay 
wait 32 seconds
repeat

**Comment by comfortplusplus** [comment]
do you want to send my projects whole code?

**Comment by comfortplusplus** [comment]
nvm i did inject your code into my project and its working flawlessly
its 3am here and i have a massive headache and brain fog, i couldnt think properly, thanks, you can close the issue now if u wish and sorry for the inconvinience.

**Comment by brunocalou** [comment]
No problem, I'm glad I could help!
